import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import Body from "@/components/Body";
import Playlist from "@/components/Playlist";
import Player from "@/components/Player";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid w-full h-[100vh] grid-cols-3">
        <Header />
        <div className="col-start-1 col-end-4 row-start-1 row-end-2"></div>
        <Player />
      </div>
    </>
  );
}
